require 'porgy'

require 'pathname'

porgy_file = Pathname.new(__dir__) + 'porgy.yml'
config = Porgy::Config.load(porgy_file)

config.targets.each do |target|
  namespace :build_ do
    task target.name => [target.output]
    file target.output => target.sources do
      Porgy::Builder.build(target.name, config)
    end
  end
end

desc "Build target [target=#{config.target_names.join('|')} (default=#{config.default_target})]"
task :build, [:target] do |task, args|
  target_name = args[:target] || config.default_target
  Rake::Task["build_:#{target_name}"].invoke
end
